twig:
    paths:            ['%kernel.project_dir%/templates']
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_custom_file.html.twig'
        - 'VichUploaderBundle/Form/fields.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
